import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
titanic_data = pd.read_csv('titanic.csv')
print(titanic_data.info())
print(titanic_data.describe())
print(titanic_data.isnull().sum())
titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)
titanic_data.drop('Cabin', axis=1, inplace=True)
titanic_data.dropna(subset=['Embarked'], inplace=True)
titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)
titanic_data.drop('Cabin', axis=1, inplace=True)
titanic_data.dropna(subset=['Embarked'], inplace=True)
plt.figure(figsize=(10, 6))
sns.heatmap(titanic_data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()
plt.figure(figsize=(10, 5))
sns.histplot(titanic_data['Age'], bins=30, kde=True)
plt.title('Age Distribution')
plt.show()
plt.figure(figsize=(10, 5))
sns.boxplot(x='Pclass', y='Fare', data=titanic_data)
plt.title('Boxplot of Fare by Passenger Class')
plt.show()
plt.figure(figsize=(10, 5))
sns.countplot(x='Pclass', hue='Survived', data=titanic_data)
plt.title('Count of Survived by Passenger Class')
plt.show()
